name: Deployment Workflow
on:
  push:
    branches: [master]

jobs:
  job_one:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./ribbon-fe
        run: yarn install

      - name: Build
        working-directory: ./ribbon-fe
        run: yarn build
        env:
          CI: false

      - name: Deploy
        working-directory: ./ribbon-fe
        run: scp -r /build/ daniel@172.104.165.240:~

