name: Deployment Workflow
on:
  push:
    branches: [master]

jobs:
  job_one:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Change directory
        run: pwd

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
